---
- summary: |
    Успешная регистрация пользователя
  status: fail
---
- summary: |
    Проверка входа пользователя с существующими логином и паролем
  status: fail
---
  - summary: |
    Проверка входа пользователя с несуществующими логином и паролем
  status: fail
---
- summary: |
    Проверка поиска товара по ключевому слову
  status: pass

  bugreports:
  - summary: |
      Адаптивность верстки
    environment: |
      https://products-store-git-v2bugfixes-hexlet-components.vercel.app/
    steps-to-reproduce: |
      - Открыта главная страница магазина с каталогом товаров
      - В окне "Поиск" вводим слово "plant"
    expected-result: |
       На странице с каталогом товаров отобразиись товары в названии которых есть слово "plant"
    actual-result: |
      Фильтр работает корректно, проблемы с версткой
---
- summary: |
    Проверка поиска товара по категории
  status: pass
---
- summary: |
    Проверка фильтрации товаров
  status: fail

    bugreports:
  - summary: |
      Фильтр не работает
    environment: |
      https://products-store-git-v2bugfixes-hexlet-components.vercel.app/
    steps-to-reproduce: |
     - Открыта главная страница магазина с каталогом товаров
     - выбрать нужные значения фильтра:
        Производитель: Apple, Huawei
        Цена: от 500 до 1000
    expected-result: |
      На главной странице отображаются товары, которые отвечают требованиям фильтрации
    actual-result: |
      Ничего не происходит, фильтр не работает

  - summary: |
    Проверка возможности просмотра подробной информации о товаре
  status: pass
---
- summary: |
    Проверка возможности добавления товаров в корзину
  status: pass
  ---
- summary: |
    Проверка возможности просмотра содержимого корзины
  status: pass
---
- summary: |
    Проверка нажатия на лого "Hexlet Store" для открытия главной страницы
  status: pass
---
  - summary: |
    Проверка пропорций изображений в карточках товара
  status: pass
---
- summary: |
    Проверка расположения кнопки "Оформить заказ" в корзине
  status: fail

  - summary: |
    Кнопка "Оформить заказ" расположена не верно
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - найти кнопку "Оформить заказ"
  expected-result: |
    Кнопка "Оформить заказ" в корзине расположена снизу и справа от таблицы с товарами
  actual-result: |
    Кнопка "Оформить заказ" в корзине расположена по центру сверху от таблицы с товарами
  ---
- summary: |
    Проверить правильное расположение кнопок "Очистить корзину" и "Продолжить покупки"
  status: fail

  - summary: |
    Кнопки "Очистить корзину" и "Продолжить покупки" расположены не верно
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - найти кнопку "Очистить корзину" и "Продолжить покупки"
  expected-result: |
    Кнопки "Очистить корзину" и "Продолжить покупки" в корзине расположена по центру снизу от таблицы с товарами
  actual-result: |
    Кнопки "Очистить корзину" и "Продолжить покупки" в корзине расположена сверху от таблицы с товарами

---
- summary: |
    Проверить формат таблицы со списком товаров во вкладке "Корзина"
  status: fail

  - summary: |
    Таблица с товарами во вкладке "Корзина" отформатирована неудобно для пользователя
  environment: |
   https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - Оценить форматирование в корзине
  expected-result: |
    Таблица в корзине со списком товаров отформатирована удобно для пользователя
  actual-result: |
    Таблица в корзине со списком товаров отформатирована неудобно: кнопка "Удалить" и столб с количеством товаров съезжают вправо
---
  - summary: |
    Проверить наличие шапки таблицы товаров во вкладке "Корзина"
  status: fail

  - summary: |
    Отсутствует шапка таблицы товаров во вкладке "Корзина"
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - Найти шапку в таблице с товарами
  expected-result: |
    Таблица имеет шапку со столбцами "Название товара", "Количество", "Цена", "Удалить"
  actual-result: |
    Шапка в таблице отсутствует
---
- summary: |
    Проверка возможности редактирования списка товаров по количеству единиц
  status: fail

  - summary: |
    Отсутствует возможность редактирования списка товаров по количеству единиц
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину по 3 штуки
    - Перейти в корзину
    - Попробовать отредактировать список товаров по количеству единиц
  expected-result: |
    В корзине есть возможность редактирования списка товаров по количеству единиц
  actual-result: |
    В корзине отсутствует возможность редактирования списка товаров по количеству единиц
  ---
- summary: |
    Проверить возможность удаления товара, нажав на кнопку "Удалить"
  status: pass
---
- summary: |
    Проверка формы, которая появляется после нажатия на кнопку "Оформить заказ"
  status: fail

  - summary: |
    Отсутствует формы, которая появляется после нажатия на кнопку "Оформить заказ"
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - Нажать кнопку "Оформить заказ"
  expected-result: |
    Всплывает окно с формой, где необходимо заполнить адрес
  actual-result: |
    Отсутствует форма для заполнения адреса

---
  - summary: |
    Проверка, что после оформления заказа появляется окно "Заказ успешно оформлен"
  status: fail

  - summary: |
    После оформления заказа появляется окно "Заказ успешно оформлен", но не на том этапе
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - Нажать кнопку "Оформить заказ"
  expected-result: |
    После ввода адреса доставки появляется окно "Заказ успешно оформлен"
  actual-result: |
    Окно "Заказ успешно оформлен" появляется до формы, где пользователь должен ввести адрес доставки
    
   - summary: |
    Не закрывается окно "Заказ успешно оформлен" после нажатия крестика в верзнем правом углу
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - Нажать кнопку "Оформить заказ"
  expected-result: |
    После нажатия крестика окно закрывается
  actual-result: |
    После нажатия крестика ничего не происходит

- summary: |
    Проверка правильной работы кнопки "Продолжить покупки"
  status: pass
  ---
- summary: |
    Проверка правильной работы кнопки "Очистить корзину"
  status: pass
---
- summary: |
    Проверка цвета кнопки "Очистить корзину"
  status: pass
---
  - summary: |
   Проверка цвета кнопки "Оформить заказ"
  status: pass
---
- summary: |
    Проверка расположения Общей суммы заказа в корзине
  status: fail

  - summary: |
    Неправильное расположения "Общей суммы" заказа в корзине
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
  steps-to-reproduce: |
    - Открыть главную страницу интернет-магазина
    - Добавить несколько товаров в корзину
    - Перейти в корзину
    - Найти где отображается общая сумма всех товаров
  expected-result: |
    Общая сумма всего заказа в корзине отображается под таблицей со списком товаров справа
  actual-result: |
    Общая сумма всего заказа в корзине отображается над таблицей со списком товаров справа
  ---
- summary: |
    Проверка иконок во вкладке "Язык"
  status: fail

  - summary: |
    Отсутствуют иконки языков в меня "Язык"
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/
  steps-to-reproduce: |
    - открыть сайт интернет-магазина
    - нажать на меню "Язык"
    - проверить наличие иконок
  expected-result: |
    Отображаются все иконки во вкладке "Язык"
  actual-result: |
    Иконки отсутствуют
  ---
- summary: |
    Проверка работы кнопки "В корзину"
  status: fail

  - summary: |
    Кнопка "В корзину" не меняет цвет и надпись при добавлении товара в корзину
  environment: |
    https://products-store-git-v2bugfixes-hexlet-components.vercel.app/
  steps-to-reproduce: |
    - Открыть сайт интернет магазина
    - нажать кнопку "В корзину"  под любым товаром
  expected-result: |
    Кнопка стала зеленого цвета и текст кнопки поменялся на "В корзине"
  actual-result: |
    Кнопка не изменилась
  ---
- summary: |
    Проверка работы каталога фотографий в карточке товара
  status: pass
  ---
- summary: |
    Проверка стиля карточки товара
  status: pass
  ---
- summary: |
    Проверка кнопки "Следующая" на главной странице интернет-магазина
  status: pass
  ---
- summary: |
    Проверка кнопки "Предыдущая"
  status: pass
  ---
- summary: |
   Проверка работы фильтра по категориям
  status: pass
  ---
- summary: |
    Проверка работы интернет-магазина с разной скоростью интернет подключения
  status: pass
  ---
- summary: |
   Проверка сайта на безопастность
  status: pass
    ---
- summary: |
   Проверка совместимости сайта с последними версиями браузеров
  status:  pass
  ---
- summary: |
    Проверка на способность сайта обрабатывать большое количество трафика
  status: pass
  ---
- summary: |
    Проверит доступность сайта на различных устройствах
  status: pass