---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - При нажатии на лого магазина "Hexlet Store" открывается главная страница с каталогом товаров
  - Все изображения, используемые в карточках товаров на сайте, должны быть отображены с сохранением своих пропорций, чтобы избежать искажений.
  - Кнопка "Оформить заказ" в корзине расположена снизу и справа от таблицы с товарами
  - Кнопки "Очистить корзину" и "Продолжить покупки" в корзине расположена по центру снизу от таблицы с товарами
  - Таблица в корзине со списком товаров должна быть форматирована с точки зрения удобства для пользователя
  - В корзине с таблицей списка товаров должна быть шапка "Название товара", "Количество", "Цена", "Удалить"
  - В корзине должна быть возможность редактирования списка товаров по количеству единиц
  - В корзине должна быть возможность удаления товаров
  - После нажатия на кнопку "Оформить заказ" всплывает окно с формой, где необходимо заполнить адрес
  - После оформления заказа появляется окно "Заказ успешно оформлен"
  - После нажатия на кнопку "Продолжить покупки" в корзине открывается страница каталога товаров
  - После нажатия на кнопку "Очистить корзину" в корзине удаляются все товары
  - Кнопка "Очистить корзину" в корзине должна быть красного цвета
  - Кнопка "Оформить заказ" в корзине должна быть зеленого цвета
  - Общая сумма всего заказа в корзине отображается под таблицей со списком товаров справа
  - Отображаются все иконки во вкладке "Язык"
  - После добавления товара в корзину кнопка "В корзину" становится зеленого цвета и текст меняется на "В корзине"
  - В карточке товара главная фотография должна заменяться на фотографию из списка по клику
  - Все карточки товаров должны иметь единый стиль
  - На главной странице с каталогом товаров на первой странице  внизу есть только кнопка "Следующая" страница
  - На главной странице с каталогом товаров на последней странице  внизу есть только кнопка "Предыдущая" страница
  - На главной странице в списке "Категория" можно сбросить выбранную категорию для отображения всех категорий

implicit:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах