---
- summary: |
    Успешная регистрация пользователя
  status: fail
---
- summary: |
    Проверка входа пользователя с существующими логином и паролем
  status: fail
---
  - summary: |
    Проверка входа пользователя с несуществующими логином и паролем
  status: fail
---
- summary: |
    Проверка поиска товара по ключевому слову
  status: pass
---
- summary: |
    Проверка поиска товара по категории
  status: pass
---
- summary: |
    Проверка фильтрации товаров
  status: pass
---
  - summary: |
    Проверка возможности просмотра подробной информации о товаре
  status: pass
---
- summary: |
    Проверка возможности добавления товаров в корзину
  status: pass
  ---
- summary: |
    Проверка возможности просмотра содержимого корзины
  status: pass
---
- summary: |
    Проверка нажатия на лого "Hexlet Store" для открытия главной страницы
  status: fail
---
  - summary: |
    Проверка пропорций изображений в карточках товара
  status: fail
---
- summary: |
    Проверка расположения кнопки "Оформить заказ" в корзине
  status: fail
  ---
- summary: |
    Проверить правильное расположение кнопок "Очистить корзину" и "Продолжить покупки"
  status: fail
---
- summary: |
    Проверить формат таблицы со списком товаров во вкладке "Корзина"
  status: fail
---
  - summary: |
    Проверить наличие шапки таблицы товаров во вкладке "Корзина"
  status: fail
---
- summary: |
    Проверка возможности редактирования списка товаров по количеству единиц
  status: fail
  ---
- summary: |
    Проверить возможность удаления товара, нажав на кнопку "Удалить"
  status: pass
---
- summary: |
    Проверка формы, которая появляется после нажатия на кнопку "Оформить заказ"
  status: fail
---
  - summary: |
    Проверка, что после оформления заказа появляется окно "Заказ успешно оформлен"
  status: fail
---
- summary: |
    Проверка правильной работы кнопки "Продолжить покупки"
  status: pass
  ---
- summary: |
    Проверка правильной работы кнопки "Очистить корзину"
  status: pass
---
- summary: |
    Проверка цвета кнопки "Очистить корзину"
  status: pass
---
  - summary: |
   Проверка цвета кнопки "Оформить заказ"
  status: pass
---
- summary: |
    Проверка расположения Общей суммы заказа в корзине
  status: fail
  ---
- summary: |
    Проверка иконок во вкладке "Язык"
  status: fail
  ---
- summary: |
    Проверка работы кнопки "В корзину"
  status: fail
  ---
- summary: |
    Проверка работы каталога фотографий в карточке товара
  status: fail
  ---
- summary: |
    Проверка стиля карточки товара
  status: fail
  ---
- summary: |
    Проверка кнопки "Следующая" на главной странице интернет-магазина
  status: fail
  ---
- summary: |
    Проверка кнопки "Предыдущая"
  status: fail
  ---
- summary: |
   Проверка работы фильтра по категориям
  status: fail
  ---
- summary: |
    Проверка работы интернет-магазина с разной скоростью интернет подключения
  status: 
  ---
- summary: |
   Проверка сайта на безопастность
  status:
    ---
- summary: |
   Проверка совместимости сайта с последними версиями браузеров
  status: 
  ---
- summary: |
    Проверка на способность сайта обрабатывать большое количество трафика
  status: 
  ---
- summary: |
    Проверит доступность сайта на различных устройствах
  status: